return {
  ensure_installed = {
    "stylua",
    "shellcheck",
    "eslint_d",
    "js-debug-adapter",
    "json-lsp",
    "lua-language-server",
    "prettier",
    "rustywind",
    "typescript-language-server",
    "gopls",
    "delve",
    "golines",
    "clangd",
    "codelldb",
    "angular-language-server",
    "ansible-language-server",
  },
}
